### PR TITLE
Added Unity TDD Tests and cleaned up pfio.h to be a minimal interface

### PR DESCRIPTION
**Pull request by nscooling**
Hi Thomas, 
I've just started playing with the piface and was looking at your supplied C wrapper functions. 
I've had a go at cleaning them up. Initially fairly simple (i.e. you should never use char for 8-bit data as it's neither signed or unsigned) and used the useful C header <stdint.h> for uint8_t as a better type for byte data.
I removed all the stuff from the header that shouldn't really be there (you only put stuff in a header of use to the client).
I haven't changed any basic behaviour but have some plans.
If you've never see Unity as a C based TDD framework it's vey useful.
Thanks for doing the difficult bit,
Regards, Niall.

### CODE REVIEW

**Comment by tompreston** [comment]
That's great, thanks. I'll merge in the changes.

By the way, we don't really maintain this repository any more. We have more up to date Python Libraries [here](https://github.com/piface) and [Gordon's WiringPi](http://wiringpi.com/) has excellent support for PiFace.

**Comment by nscooling** [comment]
Okay, thanks I'll have a look at Gordon's stuff as well.

I was looking at doing some stuff around SWIG just for the fun of it. I was guessing most people will be using Python anyway but it was something to keep me busy.

Cheers

**Comment by tompreston** [comment]
Are there any special compiler flags you used? Some people are having issues: https://github.com/thomasmacpherson/piface/issues/13

**Comment by nscooling** [comment]
Hi Thomas,

I'm using the -std=c99 but that won't remove the warnings.

The warnings are being generated (correctly) because of the uint8_t being passed to a string function. All that's needed is to cast the type. You're okay with why not to use plain chars for bytes?

I'll have a play here and let you know.

Cheers,

Niall.

**Comment by nscooling** [comment]
Just looked at it and it's my mistake, I did a global find/replace for char with uint8_t, but in this case it should be a char. I'll check for any others.

I'll fix it and push the request.

Sorry,

Niall.

**Pull request merged**
